name: runshaw
description: "My Runshaw mobile app"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.5+3

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  appwrite: ^13.0.0
  mobile_scanner: ^6.0.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  icalendar_parser: ^2.1.0
  flutter_slider_drawer: ^2.1.3
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  http: ^1.2.2
  dropdown_button2: ^2.3.9
  firebase_core: ^3.8.0
  onesignal_flutter: ^5.2.9
  url_launcher: ^6.3.1
  video_player: ^2.9.2

  flutter_cache_manager: any
  crop_your_image: ^2.0.0
  package_info_plus: ^8.1.4
  flutter_image_map: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/map/
