name: runshaw
description: "My Runshaw mobile app"
publish_to: "none" # don't remove this line! we don't want to accidentally publish this app to pub.dev

version: 1.4.5+39

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  appwrite: ^22.0.0
  mobile_scanner: ^7.1.4
  google_fonts: ^8.0.2
  provider: ^6.1.5+1
  icalendar_parser: ^2.1.0
  flutter_slider_drawer: ^3.0.2
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  http: ^1.6.0
  dropdown_button2: ^3.0.0
  onesignal_flutter: ^5.4.4
  url_launcher: ^6.3.1
  video_player: ^2.11.1
  crop_your_image: ^2.0.0
  package_info_plus: ^9.0.0
  flutter_image_map: ^1.0.1
  pub_semver: ^2.1.5
  skeletonizer: ^2.0.1
  posthog_flutter: ^5.20.0
  device_info_plus: ^12.3.0
  gaimon: ^1.4.2
  flutter_cache_manager: ^3.4.1
  cronet_http: ^1.8.0
  cupertino_http: ^2.4.0
  fetch_client: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.8.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/map/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
