name: runshaw
description: "My Runshaw mobile app"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  appwrite: ^13.0.0
  mobile_scanner: ^6.0.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  icalendar_parser: ^2.1.0
  flutter_slider_drawer: ^2.1.3
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
