name: runshaw
description: "My Runshaw mobile app"
publish_to: "none" # don't remove this line! we don't want to accidentally publish this app to pub.dev

version: 1.3.16+25

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  appwrite: ^18.0.0
  mobile_scanner: ^7.0.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  icalendar_parser: ^2.1.0
  flutter_slider_drawer: ^3.0.2
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  http: ^1.2.2
  dropdown_button2: ^2.3.9
  firebase_core: ^3.8.0
  onesignal_flutter: ^5.3.0
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  crop_your_image: ^2.0.0
  package_info_plus: ^8.0.0
  flutter_image_map: ^1.0.1
  aptabase_flutter: ^0.4.1
  pub_semver: ^2.1.5
  skeletonizer: ^2.0.1
  # posthog_flutter: ^5.0.0  # TODO: migrate to posthog for analytics!

dependency_overrides:
  # aptabase_flutter hasn't been upgraded in a while, so depends on an older version of device_info_plus;
  # we'll override it.
  device_info_plus: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/map/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
