// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw_TigmDWNsrSfMEzCcV2851s1sZ1UgvI',
    appId: '1:463256926506:web:125164dae499ba95aa4653',
    messagingSenderId: '463256926506',
    projectId: 'my-runshaw',
    authDomain: 'my-runshaw.firebaseapp.com',
    storageBucket: 'my-runshaw.firebasestorage.app',
    measurementId: 'G-7F3N5KXSLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcjXnFtNtleU9qoBtX2swoahVlWd5W2_0',
    appId: '1:463256926506:android:8eb950980fcd652aaa4653',
    messagingSenderId: '463256926506',
    projectId: 'my-runshaw',
    storageBucket: 'my-runshaw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGZhjeae-8GbOnE9-pcIg-NoJoyGfK7ic',
    appId: '1:463256926506:ios:ecd2b11d98c8adc5aa4653',
    messagingSenderId: '463256926506',
    projectId: 'my-runshaw',
    storageBucket: 'my-runshaw.firebasestorage.app',
    iosBundleId: 'com.daniel.runshaw',
  );
}
