import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_image_map/flutter_image_map.dart';
import 'package:posthog_flutter/posthog_flutter.dart';
import 'package:runshaw/pages/main/subpages/map/individual_map.dart';
import 'package:runshaw/pages/main/subpages/map/locations.dart';
import 'package:runshaw/utils/vendor/interactive_viewer/zoomable_interactive_viewer.dart';
import 'package:shared_preferences/shared_preferences.dart';

class MapPage extends StatefulWidget {
  const MapPage({super.key});

  @override
  State<MapPage> createState() => _MapPageState();
}

class _MapPageState extends State<MapPage> {
  final TextEditingController _searchController = TextEditingController();

  void submit() async {
    final String value = _searchController.text;
    if (value.isEmpty) {
      return;
    }
    for (final location in locations.entries) {
      for (final Map floor in location.value) {
        for (final room in floor['rooms']) {
          if (room.toLowerCase() == value.toLowerCase()) {
            await Posthog().capture(
              eventName: 'map_room_search_success',
            );
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) => IndividualBuildingMapPage(
                  fileName: floor['img'],
                  subtext: location.key,
                  referredByMainMap: true,
                ),
              ),
            );
            return;
          }
        }
      }
    }

    await Posthog().capture(
      eventName: 'map_room_search_failed',
    );

    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: const Text("Room not found"),
          content:
              const Text("Sorry, the room you searched for couldn't be found"),
          actions: <Widget>[
            TextButton(
              onPressed: () {
                Navigator.pop(context);
              },
              child: const Text("OK"),
            ),
          ],
        );
      },
    );
  }

  void maybeDisplayHelp() async {
    final SharedPreferences prefs = await SharedPreferences.getInstance();
    if (!prefs.containsKey('map_help_shown')) {
      await showDialog(
        context: context,
        builder: (BuildContext context) {
          return AlertDialog(
            title: const Text("Map Page"),
            content: const Text(
              "Tap on a building to view its floorplan. Pinch, zoom and swipe for easier navigation. Search for specific rooms via the bottom right button. This page uses landscape mode so the floorplans are easier to view.",
            ),
            actions: <Widget>[
              TextButton(
                onPressed: () {
                  Navigator.pop(context);
                },
                child: const Text("OK"),
              ),
            ],
          );
        },
      );
      await prefs.setBool('map_help_shown', true);
    }
  }

  @override
  Widget build(BuildContext context) {
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,
    ]);

    final htmlDataRegions = ImageMapRegion.fromHtml(
      '''
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="campus.png" usemap="#image-map">

<map name="image-map">
    <area title="Tyndale"                 href="tyndale" coords="181,1892,653,1543" shape="rect">
    <area title="Ferndale"                href="ferndale" coords="665,1892,1136,1543" shape="rect">
    <area title="Silverdale"              href="silverdale" coords="1236,1949,1708,1550" shape="rect">
    <area title="Mardale"                 href="mardale" coords="1757,2067,2229,1541" shape="rect">
    <area title="Octagon"                 href="octagon" coords="2278,1877,2750,1540" shape="rect">
    <area title="Langdale &amp; Coniston" href="Langdale & Coniston" coords="2812,2013,3391,1541" shape="rect">
    <area title="Patterdale"              href="patterdale" coords="2924,1478,3396,1195" shape="rect">
    <area title="Buttermere"              href="buttermere" coords="2919,1024,3391,709" shape="rect">
    <area title="Rydal"                   href="rydal" coords="2793,408,3391,89" shape="rect">
    <area title="Grizedale"               href="grizedale" coords="2225,409,2766,83" shape="rect">
    <area title="Dalehead"                href="dalehead" coords="1627,400,2099,85" shape="rect">
    <area title="Eskdale"                 href="eskdale" coords="745,453,1520,88" shape="rect">
    <area title="Hawkshead"               href="hawkshead" coords="181,365,649,89" shape="rect">
    <area title="Tyndale"                 href="tyndale" coords="1366,1221,1347,1240,1347,1259,1328,1278,1328,1321,1351,1324,1351,1371,1451,1374,1520,1378,1539,1355,1539,1225" shape="poly">
    <area title="Ferndale"                href="ferndale" coords="1543,1354,1531,1377,1650,1385,1669,1362,1665,1285,1543,1281" shape="poly">
    <area title="Silverdale"              href="silverdale" coords="1492,1197,1595,1197,1595,1254,1760,1254,1756,1189,1741,1085,1722,1001,1575,1001,1572,1085,1507,1082,1496,1105,1497,1193" shape="poly">
    <area title="Mardale"                 href="mardale" coords="1765,1060,1762,1344,1869,1329,1973,1376,2106,1332,2109,1202,2103,972,1819,969,1819,1064" shape="poly">
    <area title="Octagon"                 href="octagon" coords="2119,1201,2119,1286,2134,1340,2185,1337,2210,1302,2216,1270,2201,1242,2216,1217,2210,1188,2194,1166,2163,1163" shape="poly">
    <area title="Langdale &amp; Coniston" href="Langdale & Coniston" coords="2191,1154,2213,1182,2220,1208,2220,1226,2213,1245,2223,1264,2220,1290,2210,1318,2216,1343,2292,1350,2365,1359,2390,1337,2390,1280,2371,1249,2377,1151,2207,1144" shape="poly">
    <area title="Patterdale"              href="patterdale" coords="2390,1233,2396,1331,2504,1331,2519,1309,2513,1221,2488,1211,2444,1208,2444,1221,2403,1217" shape="poly">
    <area title="Buttermere"              href="buttermere" coords="2511,1174,2514,1215,2520,1221,2527,1316,2511,1341,2587,1344,2603,1322,2603,1158,2533,1151" shape="poly">
    <area title="Rydal"                   href="rydal" coords="2459,1032,2466,1083,2456,1133,2557,1136,2576,1117,2598,1086,2602,1035,2573,1029" shape="poly">
    <area title="Grizedale"               href="grizedale" coords="2450,1026,2447,1130,2428,1140,2295,1137,2295,1108,2261,1105,2254,1061,2292,1029" shape="poly">
    <area title="Dalehead"                href="dalehead" coords="1796,707,1812,795,1626,827,1620,736" shape="poly">
    <area title="Eskdale"                 href="eskdale" coords="1023,717,1039,774,1118,748,1238,1052,1272,1099,1351,1074,1364,1001,1339,922,1216,597,1133,622,1111,647,1121,679" shape="poly">
    <area title="Hawkshead"               href="hawkshead" coords="644,978,672,1073,736,1063,770,1048,792,1098,957,1041,950,972,912,864,751,921" shape="poly">
</map>
''',
      Colors.transparent,
    );

    return Scaffold(
      body: ZoomableInteractiveViewer(
        minScale: 1.0,
        maxScale: 5.0,
        constrained: true,
        boundaryMargin: EdgeInsets.zero,
        child: Padding(
            padding: const EdgeInsets.all(0.0),
            child: Center(
              child: Column(
                children: <Widget>[
                  Expanded(
                    child: ImageMap(
                      image: Image.asset('assets/img/campus.png',
                          fit: BoxFit.fitHeight),
                      onTap: (region) {
                        final List roomObjList = locations[region.link!];
                        if (roomObjList.length == 1) {
                          Navigator.push(
                            context,
                            MaterialPageRoute(
                              builder: (context) => IndividualBuildingMapPage(
                                fileName: roomObjList[0]['img'],
                                subtext: roomObjList[0]['title'],
                                referredByMainMap: true,
                              ),
                            ),
                          );
                        } else {
                          showDialog(
                            context: context,
                            builder: (BuildContext context) {
                              return AlertDialog(
                                title: Text(region.title!),
                                content: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  children: <Widget>[
                                    for (final roomObj in roomObjList)
                                      ListTile(
                                        title: Text(roomObj['title']),
                                        onTap: () {
                                          Navigator.pop(context);
                                          Navigator.push(
                                            context,
                                            MaterialPageRoute(
                                              builder: (context) =>
                                                  IndividualBuildingMapPage(
                                                fileName: roomObj['img'],
                                                subtext: roomObj['title'],
                                                referredByMainMap: true,
                                              ),
                                            ),
                                          );
                                        },
                                      ),
                                  ],
                                ),
                              );
                            },
                          );
                        }
                      },
                      regions: [
                        ...htmlDataRegions,
                      ],
                    ),
                  ),
                ],
              ),
            )),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          displaySearchMenu();
        },
        child: const Icon(Icons.search),
      ),
    );
  }

  void displaySearchMenu() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        insetPadding: const EdgeInsets.all(0),
        contentPadding: const EdgeInsets.all(0),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            SearchBar(
              controller: _searchController,
              hintText: "Search a room number...",
              autoFocus: true,
              trailing: [
                IconButton(
                    icon: const Icon(Icons.search),
                    onPressed: () {
                      Navigator.pop(context);
                      submit();
                    }),
              ],
              onSubmitted: (value) async {
                Navigator.pop(context);
                submit();
              },
            ),
          ],
        ),
      ),
    );
  }

  @override
  void initState() {
    super.initState();
    maybeDisplayHelp();
  }

  @override
  void dispose() {
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);
    super.dispose();
  }
}
